version: 2
formats: all
sphinx:
  configuration: ./conf.py
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - cmake
    - libhugetlbfs-dev
    - libsysfs-dev
  jobs:
    post_checkout:
      - git submodule sync
      - git submodule update --init --force --recursive
    post_install:
      - python -m pip install --exists-action=w --no-cache-dir -r requirements.txt
    pre_build:
      - echo "READTHEDOCS_OUTPUT=$READTHEDOCS_OUTPUT"
      - make BUILDDIR=$READTHEDOCS_OUTPUT doxygen
    post_build:
      - make BUILDDIR=$READTHEDOCS_OUTPUT doxygen_copy
